name: Workflow with Dependencies

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "This is job 2 and it depends on job 1"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "JP"
